"""Provider contract verification — Pact.

Reads the pact file generated by the TypeScript consumer tests
(orcha-convex → orcha-embedding-transformer) and verifies that the
running FastAPI service satisfies every interaction in the contract.

Usage:
    # 1. Start the service on port 5001 (or set PROVIDER_URL env var):
    #    uvicorn orcha_embeddings.presentation.main:app --port 5001
    #
    # 2. Run:
    #    pytest tests/contract/test_provider_contract.py -v

Environment variables:
    PROVIDER_URL   Base URL of the running provider (default: http://localhost:5001)
    PACT_FILE      Path to the pact JSON file (auto-detected if omitted)
"""

from __future__ import annotations

import os
from pathlib import Path

import pytest

# ── Locate the pact file ──────────────────────────────────────────────────────

_REPO_ROOT = Path(__file__).resolve().parents[4]  # orcha-agent-os/
_DEFAULT_PACT = _REPO_ROOT / "pacts" / "orcha-convex-orcha-embedding-transformer.json"

PACT_FILE = Path(os.getenv("PACT_FILE", str(_DEFAULT_PACT)))
PROVIDER_URL = os.getenv("PROVIDER_URL", "http://localhost:5001")


# ── Provider state handlers ───────────────────────────────────────────────────
# These are called before each interaction to set up the correct server state.
# For a stateless service like ours, they are no-ops — the model is always ready.

PROVIDER_STATES: dict[str, None] = {
    "the embedding service is running": None,
    "the model is loaded and ready": None,
}


# ── Pact verification ─────────────────────────────────────────────────────────

def test_provider_honours_pact_with_consumer() -> None:
    """Verify the FastAPI provider satisfies the consumer pact contract.

    This test will:
    1. Read the pact file (generated by the TypeScript consumer tests).
    2. Replay each interaction against the running provider at PROVIDER_URL.
    3. Assert that every response matches the contract exactly.
    """
    try:
        from pact import Verifier
    except ImportError:
        pytest.skip(
            "pact-python is not installed. "
            "Run: pip install pact-python  and re-run this test."
        )

    if not PACT_FILE.exists():
        pytest.skip(
            f"Pact file not found: {PACT_FILE}\n"
            "Run the TypeScript consumer tests first:\n"
            "  npx jest tests/contract/embedding.consumer.test.ts"
        )

    verifier = Verifier(
        provider="orcha-embedding-transformer",
        provider_base_url=PROVIDER_URL,
    )

    output, _ = verifier.verify_pacts(
        str(PACT_FILE),
        provider_states_setup_url=None,   # stateless service — no setup endpoint needed
        verbose=True,
    )

    assert output == 0, (
        "Provider verification FAILED. "
        "The FastAPI service does not satisfy the consumer contract. "
        f"Check the output above for details."
    )
