/**
 * STUB — Auto-generated by `pnpm convex:dev`.
 * Provides a typed `api` object stub until your Convex project is connected.
 */

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export declare const api: any;

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export declare const internal: any;
