/**
 * STUB — Auto-generated by `pnpm convex:dev`.
 * Provides minimal types for the DataModel and Id so TypeScript
 * is satisfied before your Convex project is connected.
 */

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export type DataModel = any;

/**
 * A Convex document ID, typed by table name.
 * In the real generated file this is a branded string.
 */
export type Id<TableName extends string> = string & {
    readonly __tableName: TableName;
};

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export type Doc<TableName extends string> = any;
