/**
 * STUB — This file is auto-generated by `pnpm convex:dev`.
 * Manually created to satisfy TypeScript before the Convex project is
 * connected. Run `pnpm convex:dev` to replace with the real generated file.
 */

/* eslint-disable @typescript-eslint/no-explicit-any */

// ─── Minimal ctx shapes ────────────────────────────────────────────────────

type DB = {
    query(table: string): any;
    get(id: any): Promise<any>;
    insert(table: string, doc: any): Promise<any>;
    patch(id: any, patch: any): Promise<void>;
    delete(id: any): Promise<void>;
};

type MutationCtx = { db: DB; storage: any; auth: any; scheduler: any };
type QueryCtx = { db: DB; storage: any; auth: any };
type ActionCtx = { runQuery: any; runMutation: any; runAction: any; auth: any };

// ─── Builder types ─────────────────────────────────────────────────────────

type MutationConfig = { args?: any; handler: (ctx: MutationCtx, args: any) => any };
type QueryConfig = { args?: any; handler: (ctx: QueryCtx, args: any) => any };
type ActionConfig = { args?: any; handler: (ctx: ActionCtx, args: any) => any };

type Builder<Cfg> = (config: Cfg) => any;

// ─── Exports matching what `_generated/server` provides ───────────────────

export declare const mutation: Builder<MutationConfig>;
export declare const query: Builder<QueryConfig>;
export declare const action: Builder<ActionConfig>;
export declare const internalMutation: Builder<MutationConfig>;
export declare const internalQuery: Builder<QueryConfig>;
export declare const internalAction: Builder<ActionConfig>;
