"use client";

/**
 * app/home/page.tsx
 *
 * Onboarding: shown when the signed-in user has no Clerk organization yet.
 * Lets them create their first workspace using Clerk's createOrganization API.
 */

import { useState, useEffect } from "react";
import { useRouter } from "next/navigation";
import { useOrganizationList, useUser } from "@clerk/nextjs";
import { useMutation } from "convex/react";
import { api } from "@/convex/_generated/api";
import { useMantineColorScheme } from "@mantine/core";
import { ThemeToggle } from "@/components/ThemeToggle";

function OrchaLogo() {
  return (
    <svg width="40" height="40" viewBox="0 0 36 36" fill="none">
      <circle cx="18" cy="18" r="17" stroke="url(#hg)" strokeWidth="2" />
      <circle cx="18" cy="18" r="10" stroke="url(#hg)" strokeWidth="1.5" opacity="0.45" />
      <path d="M18 8 L22 14 L18 12 L14 14 Z" fill="url(#hg)" />
      <path d="M18 28 L14 22 L18 24 L22 22 Z" fill="url(#hg)" opacity="0.65" />
      <circle cx="18" cy="18" r="3" fill="url(#hg)" />
      <defs>
        <linearGradient id="hg" x1="1" y1="1" x2="35" y2="35" gradientUnits="userSpaceOnUse">
          <stop stopColor="#9333ea" />
          <stop offset="1" stopColor="#c084fc" />
        </linearGradient>
      </defs>
    </svg>
  );
}

export default function HomePage() {
  const router = useRouter();
  const { user } = useUser();
  const { createOrganization, setActive } = useOrganizationList();
  const upsertOrg = useMutation(api.organizations.upsertFromClerk);
  const { colorScheme } = useMantineColorScheme();

  const [mounted, setMounted] = useState(false);
  const [name, setName]       = useState("");
  const [error, setError]     = useState("");
  const [loading, setLoading] = useState(false);

  useEffect(() => {
    setMounted(true);
  }, []);

  const isDark = !mounted ? true : colorScheme === "dark";

  const handleCreate = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!name.trim()) { setError("Workspace name is required."); return; }
    if (!createOrganization) { setError("Organization creation unavailable."); return; }

    setLoading(true);
    setError("");
    try {
      const org = await createOrganization({ name: name.trim() });
      
      // JIT Sync to Convex
      try {
        await upsertOrg({
          clerkOrgId: org.id,
          name: org.name,
          slug: org.slug || org.id,
        });
      } catch (err) {
        console.error("Failed to JIT sync org during creation:", err);
      }

      if (setActive) {
        await setActive({ organization: org.id });
      }
      // slug is auto-generated by Clerk from the name, fallback to id if not immediately available
      router.replace(`/${org.slug || org.id}/chat`);
    } catch (err: unknown) {
      setError(err instanceof Error ? err.message : "Failed to create workspace.");
      setLoading(false);
    }
  };

  const inputStyle: React.CSSProperties = {
    width: "100%",
    height: "44px",
    background: isDark ? "rgba(255,255,255,0.05)" : "rgba(0,0,0,0.03)",
    border: isDark ? "1px solid rgba(255,255,255,0.09)" : "1px solid rgba(0,0,0,0.09)",
    borderRadius: "0.6rem",
    color: isDark ? "#fff" : "#1f2937",
    padding: "0 14px",
    fontSize: "14px",
    outline: "none",
    boxSizing: "border-box",
    transition: "border-color 0.2s, box-shadow 0.2s",
  };

  const bg = isDark ? "#07050f" : "#fcfbfe";
  const titleColor = isDark ? "text-white" : "text-slate-900";
  const subtextColor = isDark ? "rgba(255,255,255,0.4)" : "rgba(15,23,42,0.64)";
  const labelColor = isDark ? "rgba(255,255,255,0.7)" : "rgba(15,23,42,0.7)";
  const footerColor = isDark ? "rgba(255,255,255,0.22)" : "rgba(15,23,42,0.45)";

  return (
    <div
      className="flex h-screen w-full items-center justify-center px-6 relative"
      style={{ background: bg }}
    >
      <div className="absolute top-4 right-4 z-50">
        <ThemeToggle />
      </div>

      <div style={{ width: "100%", maxWidth: 420 }}>
        {/* Logo + welcome */}
        <div className="flex flex-col items-center gap-3 mb-10 text-center">
          <OrchaLogo />
          <div>
            <p className={`${titleColor} font-bold text-2xl mt-2`}>
              Welcome{user?.firstName ? `, ${user.firstName}` : ""}!
            </p>
            <p className="text-sm mt-1" style={{ color: subtextColor }}>
              Create your first workspace to get started.
            </p>
          </div>
        </div>

        {/* Create workspace form */}
        <form onSubmit={handleCreate} style={{ display: "flex", flexDirection: "column", gap: 16 }}>
          <div style={{ display: "flex", flexDirection: "column", gap: 6 }}>
            <label
              htmlFor="workspace-name"
              style={{ fontSize: 13, fontWeight: 500, color: labelColor }}
            >
              Workspace Name
            </label>
            <input
              id="workspace-name"
              type="text"
              placeholder="e.g. Acme Corp"
              value={name}
              onChange={(e) => setName(e.target.value)}
              style={inputStyle}
              onFocus={(e) => {
                e.currentTarget.style.border = "1px solid rgba(147,51,234,0.5)";
                e.currentTarget.style.boxShadow = "0 0 0 3px rgba(147,51,234,0.12)";
              }}
              onBlur={(e) => {
                e.currentTarget.style.border = isDark ? "1px solid rgba(255,255,255,0.09)" : "1px solid rgba(0,0,0,0.09)";
                e.currentTarget.style.boxShadow = "none";
              }}
            />
          </div>

          {error && (
            <p style={{ fontSize: 13, color: "#ef4444", background: isDark ? "rgba(239,68,68,0.08)" : "rgba(239,68,68,0.04)", border: "1px solid rgba(239,68,68,0.18)", borderRadius: "0.6rem", padding: "10px 14px" }}>
              {error}
            </p>
          )}

          <button
            type="submit"
            disabled={loading}
            style={{
              height: 44,
              borderRadius: "0.6rem",
              border: "none",
              background: loading ? "rgba(147,51,234,0.5)" : "linear-gradient(135deg, #9333ea, #7c3aed)",
              color: "#fff",
              fontWeight: 600,
              fontSize: 14,
              cursor: loading ? "not-allowed" : "pointer",
              display: "flex",
              alignItems: "center",
              justifyContent: "center",
              gap: 8,
              boxShadow: loading ? "none" : isDark ? "0 0 24px rgba(147,51,234,0.4)" : "0 0 24px rgba(147,51,234,0.2)",
              transition: "opacity 0.2s",
            }}
          >
            {loading ? (
              <>
                <svg className="animate-spin w-4 h-4" viewBox="0 0 24 24" fill="none">
                  <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" />
                  <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8v4a4 4 0 00-4 4H4z" />
                </svg>
                Creating workspace…
              </>
            ) : (
              "Create Workspace →"
            )}
          </button>
        </form>

        <p className="text-center text-xs mt-6" style={{ color: footerColor }}>
          You can create additional workspaces from the dashboard settings.
        </p>
      </div>
    </div>
  );
}
