/**
 * Pact Provider Verification script
 *
 * Verifies that the running FastAPI provider service matches
 * the contract generated by the consumer tests.
 *
 * Run:
 *   npx tsx tests/contract/embedding.provider.verify.ts
 */

import { Verifier } from "@pact-foundation/pact";
import path from "path";

const providerUrl = process.env.PROVIDER_URL || "http://127.0.0.1:5001";
const pactFile = path.resolve(__dirname, "../../pacts/orcha-convex-orcha-embedding-transformer.json");

console.log(`Starting Pact Provider Verification against ${providerUrl}...`);
console.log(`Using contract file: ${pactFile}`);

const verifier = new Verifier({
  provider: "orcha-embedding-transformer",
  providerBaseUrl: providerUrl,
  pactUrls: [pactFile],
  logLevel: "info",
});

verifier.verifyProvider()
  .then(() => {
    console.log("Pact Provider Verification PASSED!");
    process.exit(0);
  })
  .catch((error) => {
    console.error("Pact Provider Verification FAILED:", error);
    process.exit(1);
  });
