FROM grafana/grafana:latest

# Copy provisioning and dashboards configuration with proper ownership
COPY --chown=grafana:grafana monitoring/grafana/provisioning /etc/grafana/provisioning
COPY --chown=grafana:grafana monitoring/grafana/dashboards /var/lib/grafana/dashboards

ENV GF_SECURITY_ADMIN_USER=admin
ENV GF_SECURITY_ADMIN_PASSWORD=admin
ENV GF_USERS_ALLOW_SIGN_UP=false

EXPOSE 3000
